server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

intranet:
  penetrateUrl: http://

yypay:
  weixin:
    login:
      backUrl: https://springboot-ws6j-50829-9-1318349010.sh.run.tcloudbase.com/weixin/callBack
      appId: wx9dd11f102b89dc20
      appSecret:
  title:
  hospitalName:
  checkPdfBase:
  apiBase:
  apiUrl:
  sopAction:
  inspectionSopAction:
  pwd: 000000
  dhccAPIURl: /usr/xk/apiTemplate/dhccAPI.xml
  inspectionAPI: /usr/xk/apiTemplate/inspectionAPI.xml
  apiclientCert: /usr/xk/apiTemplate/apiclient_cert.p12
  pdfCache: /usr/xk/pdf

wx:
  mchId: 1613636825
  key: 18647373683ABCDEFGHAF06S55241941
  unifiedorder:
    notifyUrl: ${intranet.penetrateUrl}/wxPay/unifiedorderNotify

https:
  connectionTimeout: 15000
  readTimeout: 15000

logging:
  level.*: ERROR
  file:
    path: /usr/xk/logBox/
  com:
    xk:
      yypay:
        dao: debug





