package com.tencent.wxcloudrun.domain.common;

import java.util.ArrayList;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class CwCompetitionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public CwCompetitionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNull() {
            addCriterion("creator_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNotNull() {
            addCriterion("creator_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdEqualTo(String value) {
            addCriterion("creator_id =", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotEqualTo(String value) {
            addCriterion("creator_id <>", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThan(String value) {
            addCriterion("creator_id >", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("creator_id >=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThan(String value) {
            addCriterion("creator_id <", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThanOrEqualTo(String value) {
            addCriterion("creator_id <=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLike(String value) {
            addCriterion("creator_id like", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotLike(String value) {
            addCriterion("creator_id not like", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIn(List<String> values) {
            addCriterion("creator_id in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotIn(List<String> values) {
            addCriterion("creator_id not in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdBetween(String value1, String value2) {
            addCriterion("creator_id between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotBetween(String value1, String value2) {
            addCriterion("creator_id not between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIsNull() {
            addCriterion("creator_name is null");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIsNotNull() {
            addCriterion("creator_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorNameEqualTo(String value) {
            addCriterion("creator_name =", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotEqualTo(String value) {
            addCriterion("creator_name <>", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameGreaterThan(String value) {
            addCriterion("creator_name >", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("creator_name >=", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLessThan(String value) {
            addCriterion("creator_name <", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLessThanOrEqualTo(String value) {
            addCriterion("creator_name <=", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLike(String value) {
            addCriterion("creator_name like", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotLike(String value) {
            addCriterion("creator_name not like", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIn(List<String> values) {
            addCriterion("creator_name in", values, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotIn(List<String> values) {
            addCriterion("creator_name not in", values, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameBetween(String value1, String value2) {
            addCriterion("creator_name between", value1, value2, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotBetween(String value1, String value2) {
            addCriterion("creator_name not between", value1, value2, "creatorName");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andModifierIdIsNull() {
            addCriterion("modifier_id is null");
            return (Criteria) this;
        }

        public Criteria andModifierIdIsNotNull() {
            addCriterion("modifier_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifierIdEqualTo(String value) {
            addCriterion("modifier_id =", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotEqualTo(String value) {
            addCriterion("modifier_id <>", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdGreaterThan(String value) {
            addCriterion("modifier_id >", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdGreaterThanOrEqualTo(String value) {
            addCriterion("modifier_id >=", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdLessThan(String value) {
            addCriterion("modifier_id <", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdLessThanOrEqualTo(String value) {
            addCriterion("modifier_id <=", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdLike(String value) {
            addCriterion("modifier_id like", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotLike(String value) {
            addCriterion("modifier_id not like", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdIn(List<String> values) {
            addCriterion("modifier_id in", values, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotIn(List<String> values) {
            addCriterion("modifier_id not in", values, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdBetween(String value1, String value2) {
            addCriterion("modifier_id between", value1, value2, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotBetween(String value1, String value2) {
            addCriterion("modifier_id not between", value1, value2, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierNameIsNull() {
            addCriterion("modifier_name is null");
            return (Criteria) this;
        }

        public Criteria andModifierNameIsNotNull() {
            addCriterion("modifier_name is not null");
            return (Criteria) this;
        }

        public Criteria andModifierNameEqualTo(String value) {
            addCriterion("modifier_name =", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameNotEqualTo(String value) {
            addCriterion("modifier_name <>", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameGreaterThan(String value) {
            addCriterion("modifier_name >", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameGreaterThanOrEqualTo(String value) {
            addCriterion("modifier_name >=", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameLessThan(String value) {
            addCriterion("modifier_name <", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameLessThanOrEqualTo(String value) {
            addCriterion("modifier_name <=", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameLike(String value) {
            addCriterion("modifier_name like", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameNotLike(String value) {
            addCriterion("modifier_name not like", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameIn(List<String> values) {
            addCriterion("modifier_name in", values, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameNotIn(List<String> values) {
            addCriterion("modifier_name not in", values, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameBetween(String value1, String value2) {
            addCriterion("modifier_name between", value1, value2, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameNotBetween(String value1, String value2) {
            addCriterion("modifier_name not between", value1, value2, "modifierName");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameIsNull() {
            addCriterion("competition_name is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameIsNotNull() {
            addCriterion("competition_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameEqualTo(String value) {
            addCriterion("competition_name =", value, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameNotEqualTo(String value) {
            addCriterion("competition_name <>", value, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameGreaterThan(String value) {
            addCriterion("competition_name >", value, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameGreaterThanOrEqualTo(String value) {
            addCriterion("competition_name >=", value, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameLessThan(String value) {
            addCriterion("competition_name <", value, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameLessThanOrEqualTo(String value) {
            addCriterion("competition_name <=", value, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameLike(String value) {
            addCriterion("competition_name like", value, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameNotLike(String value) {
            addCriterion("competition_name not like", value, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameIn(List<String> values) {
            addCriterion("competition_name in", values, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameNotIn(List<String> values) {
            addCriterion("competition_name not in", values, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameBetween(String value1, String value2) {
            addCriterion("competition_name between", value1, value2, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionNameNotBetween(String value1, String value2) {
            addCriterion("competition_name not between", value1, value2, "competitionName");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlIsNull() {
            addCriterion("competition_img_url is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlIsNotNull() {
            addCriterion("competition_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlEqualTo(String value) {
            addCriterion("competition_img_url =", value, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlNotEqualTo(String value) {
            addCriterion("competition_img_url <>", value, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlGreaterThan(String value) {
            addCriterion("competition_img_url >", value, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("competition_img_url >=", value, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlLessThan(String value) {
            addCriterion("competition_img_url <", value, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlLessThanOrEqualTo(String value) {
            addCriterion("competition_img_url <=", value, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlLike(String value) {
            addCriterion("competition_img_url like", value, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlNotLike(String value) {
            addCriterion("competition_img_url not like", value, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlIn(List<String> values) {
            addCriterion("competition_img_url in", values, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlNotIn(List<String> values) {
            addCriterion("competition_img_url not in", values, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlBetween(String value1, String value2) {
            addCriterion("competition_img_url between", value1, value2, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionImgUrlNotBetween(String value1, String value2) {
            addCriterion("competition_img_url not between", value1, value2, "competitionImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeIsNull() {
            addCriterion("competition_time is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeIsNotNull() {
            addCriterion("competition_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeEqualTo(String value) {
            addCriterion("competition_time =", value, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeNotEqualTo(String value) {
            addCriterion("competition_time <>", value, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeGreaterThan(String value) {
            addCriterion("competition_time >", value, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeGreaterThanOrEqualTo(String value) {
            addCriterion("competition_time >=", value, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeLessThan(String value) {
            addCriterion("competition_time <", value, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeLessThanOrEqualTo(String value) {
            addCriterion("competition_time <=", value, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeLike(String value) {
            addCriterion("competition_time like", value, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeNotLike(String value) {
            addCriterion("competition_time not like", value, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeIn(List<String> values) {
            addCriterion("competition_time in", values, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeNotIn(List<String> values) {
            addCriterion("competition_time not in", values, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeBetween(String value1, String value2) {
            addCriterion("competition_time between", value1, value2, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionTimeNotBetween(String value1, String value2) {
            addCriterion("competition_time not between", value1, value2, "competitionTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationIsNull() {
            addCriterion("competition_location is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationIsNotNull() {
            addCriterion("competition_location is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationEqualTo(String value) {
            addCriterion("competition_location =", value, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationNotEqualTo(String value) {
            addCriterion("competition_location <>", value, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationGreaterThan(String value) {
            addCriterion("competition_location >", value, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationGreaterThanOrEqualTo(String value) {
            addCriterion("competition_location >=", value, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationLessThan(String value) {
            addCriterion("competition_location <", value, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationLessThanOrEqualTo(String value) {
            addCriterion("competition_location <=", value, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationLike(String value) {
            addCriterion("competition_location like", value, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationNotLike(String value) {
            addCriterion("competition_location not like", value, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationIn(List<String> values) {
            addCriterion("competition_location in", values, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationNotIn(List<String> values) {
            addCriterion("competition_location not in", values, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationBetween(String value1, String value2) {
            addCriterion("competition_location between", value1, value2, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andCompetitionLocationNotBetween(String value1, String value2) {
            addCriterion("competition_location not between", value1, value2, "competitionLocation");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeIsNull() {
            addCriterion("application_start_time is null");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeIsNotNull() {
            addCriterion("application_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeEqualTo(Date value) {
            addCriterion("application_start_time =", value, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeNotEqualTo(Date value) {
            addCriterion("application_start_time <>", value, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeGreaterThan(Date value) {
            addCriterion("application_start_time >", value, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("application_start_time >=", value, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeLessThan(Date value) {
            addCriterion("application_start_time <", value, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("application_start_time <=", value, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeIn(List<Date> values) {
            addCriterion("application_start_time in", values, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeNotIn(List<Date> values) {
            addCriterion("application_start_time not in", values, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeBetween(Date value1, Date value2) {
            addCriterion("application_start_time between", value1, value2, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("application_start_time not between", value1, value2, "applicationStartTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeIsNull() {
            addCriterion("application_end_time is null");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeIsNotNull() {
            addCriterion("application_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeEqualTo(Date value) {
            addCriterion("application_end_time =", value, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeNotEqualTo(Date value) {
            addCriterion("application_end_time <>", value, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeGreaterThan(Date value) {
            addCriterion("application_end_time >", value, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("application_end_time >=", value, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeLessThan(Date value) {
            addCriterion("application_end_time <", value, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("application_end_time <=", value, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeIn(List<Date> values) {
            addCriterion("application_end_time in", values, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeNotIn(List<Date> values) {
            addCriterion("application_end_time not in", values, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeBetween(Date value1, Date value2) {
            addCriterion("application_end_time between", value1, value2, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andApplicationEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("application_end_time not between", value1, value2, "applicationEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumIsNull() {
            addCriterion("competition_max_num is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumIsNotNull() {
            addCriterion("competition_max_num is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumEqualTo(Integer value) {
            addCriterion("competition_max_num =", value, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumNotEqualTo(Integer value) {
            addCriterion("competition_max_num <>", value, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumGreaterThan(Integer value) {
            addCriterion("competition_max_num >", value, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("competition_max_num >=", value, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumLessThan(Integer value) {
            addCriterion("competition_max_num <", value, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumLessThanOrEqualTo(Integer value) {
            addCriterion("competition_max_num <=", value, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumIn(List<Integer> values) {
            addCriterion("competition_max_num in", values, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumNotIn(List<Integer> values) {
            addCriterion("competition_max_num not in", values, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumBetween(Integer value1, Integer value2) {
            addCriterion("competition_max_num between", value1, value2, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionMaxNumNotBetween(Integer value1, Integer value2) {
            addCriterion("competition_max_num not between", value1, value2, "competitionMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumIsNull() {
            addCriterion("application_max_num is null");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumIsNotNull() {
            addCriterion("application_max_num is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumEqualTo(Integer value) {
            addCriterion("application_max_num =", value, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumNotEqualTo(Integer value) {
            addCriterion("application_max_num <>", value, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumGreaterThan(Integer value) {
            addCriterion("application_max_num >", value, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("application_max_num >=", value, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumLessThan(Integer value) {
            addCriterion("application_max_num <", value, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumLessThanOrEqualTo(Integer value) {
            addCriterion("application_max_num <=", value, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumIn(List<Integer> values) {
            addCriterion("application_max_num in", values, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumNotIn(List<Integer> values) {
            addCriterion("application_max_num not in", values, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumBetween(Integer value1, Integer value2) {
            addCriterion("application_max_num between", value1, value2, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andApplicationMaxNumNotBetween(Integer value1, Integer value2) {
            addCriterion("application_max_num not between", value1, value2, "applicationMaxNum");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupIsNull() {
            addCriterion("competition_group is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupIsNotNull() {
            addCriterion("competition_group is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupEqualTo(String value) {
            addCriterion("competition_group =", value, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupNotEqualTo(String value) {
            addCriterion("competition_group <>", value, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupGreaterThan(String value) {
            addCriterion("competition_group >", value, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupGreaterThanOrEqualTo(String value) {
            addCriterion("competition_group >=", value, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupLessThan(String value) {
            addCriterion("competition_group <", value, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupLessThanOrEqualTo(String value) {
            addCriterion("competition_group <=", value, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupLike(String value) {
            addCriterion("competition_group like", value, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupNotLike(String value) {
            addCriterion("competition_group not like", value, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupIn(List<String> values) {
            addCriterion("competition_group in", values, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupNotIn(List<String> values) {
            addCriterion("competition_group not in", values, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupBetween(String value1, String value2) {
            addCriterion("competition_group between", value1, value2, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andCompetitionGroupNotBetween(String value1, String value2) {
            addCriterion("competition_group not between", value1, value2, "competitionGroup");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeIsNull() {
            addCriterion("refund_end_time is null");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeIsNotNull() {
            addCriterion("refund_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeEqualTo(Date value) {
            addCriterion("refund_end_time =", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeNotEqualTo(Date value) {
            addCriterion("refund_end_time <>", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeGreaterThan(Date value) {
            addCriterion("refund_end_time >", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("refund_end_time >=", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeLessThan(Date value) {
            addCriterion("refund_end_time <", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("refund_end_time <=", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeIn(List<Date> values) {
            addCriterion("refund_end_time in", values, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeNotIn(List<Date> values) {
            addCriterion("refund_end_time not in", values, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeBetween(Date value1, Date value2) {
            addCriterion("refund_end_time between", value1, value2, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("refund_end_time not between", value1, value2, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeIsNull() {
            addCriterion("refund_free_time is null");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeIsNotNull() {
            addCriterion("refund_free_time is not null");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeEqualTo(Date value) {
            addCriterion("refund_free_time =", value, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeNotEqualTo(Date value) {
            addCriterion("refund_free_time <>", value, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeGreaterThan(Date value) {
            addCriterion("refund_free_time >", value, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("refund_free_time >=", value, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeLessThan(Date value) {
            addCriterion("refund_free_time <", value, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeLessThanOrEqualTo(Date value) {
            addCriterion("refund_free_time <=", value, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeIn(List<Date> values) {
            addCriterion("refund_free_time in", values, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeNotIn(List<Date> values) {
            addCriterion("refund_free_time not in", values, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeBetween(Date value1, Date value2) {
            addCriterion("refund_free_time between", value1, value2, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundFreeTimeNotBetween(Date value1, Date value2) {
            addCriterion("refund_free_time not between", value1, value2, "refundFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentIsNull() {
            addCriterion("refund_cost_percent is null");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentIsNotNull() {
            addCriterion("refund_cost_percent is not null");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentEqualTo(BigDecimal value) {
            addCriterion("refund_cost_percent =", value, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentNotEqualTo(BigDecimal value) {
            addCriterion("refund_cost_percent <>", value, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentGreaterThan(BigDecimal value) {
            addCriterion("refund_cost_percent >", value, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("refund_cost_percent >=", value, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentLessThan(BigDecimal value) {
            addCriterion("refund_cost_percent <", value, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("refund_cost_percent <=", value, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentIn(List<BigDecimal> values) {
            addCriterion("refund_cost_percent in", values, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentNotIn(List<BigDecimal> values) {
            addCriterion("refund_cost_percent not in", values, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("refund_cost_percent between", value1, value2, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andRefundCostPercentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("refund_cost_percent not between", value1, value2, "refundCostPercent");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusIsNull() {
            addCriterion("competition_status is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusIsNotNull() {
            addCriterion("competition_status is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusEqualTo(Integer value) {
            addCriterion("competition_status =", value, "competitionStatus");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusNotEqualTo(Integer value) {
            addCriterion("competition_status <>", value, "competitionStatus");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusGreaterThan(Integer value) {
            addCriterion("competition_status >", value, "competitionStatus");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("competition_status >=", value, "competitionStatus");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusLessThan(Integer value) {
            addCriterion("competition_status <", value, "competitionStatus");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusLessThanOrEqualTo(Integer value) {
            addCriterion("competition_status <=", value, "competitionStatus");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusIn(List<Integer> values) {
            addCriterion("competition_status in", values, "competitionStatus");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusNotIn(List<Integer> values) {
            addCriterion("competition_status not in", values, "competitionStatus");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusBetween(Integer value1, Integer value2) {
            addCriterion("competition_status between", value1, value2, "competitionStatus");
            return (Criteria) this;
        }

        public Criteria andCompetitionStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("competition_status not between", value1, value2, "competitionStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cw_competition
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cw_competition
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}