package com.tencent.wxcloudrun.domain.common;

import java.util.Date;

public class CwCommonPlayer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.player_name
     *
     * @mbg.generated
     */
    private String playerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.player_sex
     *
     * @mbg.generated
     */
    private Integer playerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.player_age
     *
     * @mbg.generated
     */
    private Integer playerAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_common_player.player_id_card
     *
     * @mbg.generated
     */
    private String playerIdCard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.id
     *
     * @return the value of cw_common_player.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.id
     *
     * @param id the value for cw_common_player.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.is_deleted
     *
     * @return the value of cw_common_player.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.is_deleted
     *
     * @param isDeleted the value for cw_common_player.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.creator_id
     *
     * @return the value of cw_common_player.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.creator_id
     *
     * @param creatorId the value for cw_common_player.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.creator_name
     *
     * @return the value of cw_common_player.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.creator_name
     *
     * @param creatorName the value for cw_common_player.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.gmt_create
     *
     * @return the value of cw_common_player.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.gmt_create
     *
     * @param gmtCreate the value for cw_common_player.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.modifier_id
     *
     * @return the value of cw_common_player.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.modifier_id
     *
     * @param modifierId the value for cw_common_player.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.modifier_name
     *
     * @return the value of cw_common_player.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.modifier_name
     *
     * @param modifierName the value for cw_common_player.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.gmt_modified
     *
     * @return the value of cw_common_player.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.gmt_modified
     *
     * @param gmtModified the value for cw_common_player.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.openid
     *
     * @return the value of cw_common_player.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.openid
     *
     * @param openid the value for cw_common_player.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.user_id
     *
     * @return the value of cw_common_player.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.user_id
     *
     * @param userId the value for cw_common_player.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.player_name
     *
     * @return the value of cw_common_player.player_name
     *
     * @mbg.generated
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.player_name
     *
     * @param playerName the value for cw_common_player.player_name
     *
     * @mbg.generated
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.player_sex
     *
     * @return the value of cw_common_player.player_sex
     *
     * @mbg.generated
     */
    public Integer getPlayerSex() {
        return playerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.player_sex
     *
     * @param playerSex the value for cw_common_player.player_sex
     *
     * @mbg.generated
     */
    public void setPlayerSex(Integer playerSex) {
        this.playerSex = playerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.player_age
     *
     * @return the value of cw_common_player.player_age
     *
     * @mbg.generated
     */
    public Integer getPlayerAge() {
        return playerAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.player_age
     *
     * @param playerAge the value for cw_common_player.player_age
     *
     * @mbg.generated
     */
    public void setPlayerAge(Integer playerAge) {
        this.playerAge = playerAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_common_player.player_id_card
     *
     * @return the value of cw_common_player.player_id_card
     *
     * @mbg.generated
     */
    public String getPlayerIdCard() {
        return playerIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_common_player.player_id_card
     *
     * @param playerIdCard the value for cw_common_player.player_id_card
     *
     * @mbg.generated
     */
    public void setPlayerIdCard(String playerIdCard) {
        this.playerIdCard = playerIdCard;
    }
}