package com.tencent.wxcloudrun.domain.common;

import java.util.Date;

public class CwCompetitionCharge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.charge_name
     *
     * @mbg.generated
     */
    private String chargeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition_charge.competition_id
     *
     * @mbg.generated
     */
    private Integer competitionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.id
     *
     * @return the value of cw_competition_charge.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.id
     *
     * @param id the value for cw_competition_charge.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.is_deleted
     *
     * @return the value of cw_competition_charge.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.is_deleted
     *
     * @param isDeleted the value for cw_competition_charge.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.creator_id
     *
     * @return the value of cw_competition_charge.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.creator_id
     *
     * @param creatorId the value for cw_competition_charge.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.creator_name
     *
     * @return the value of cw_competition_charge.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.creator_name
     *
     * @param creatorName the value for cw_competition_charge.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.gmt_create
     *
     * @return the value of cw_competition_charge.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.gmt_create
     *
     * @param gmtCreate the value for cw_competition_charge.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.modifier_id
     *
     * @return the value of cw_competition_charge.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.modifier_id
     *
     * @param modifierId the value for cw_competition_charge.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.modifier_name
     *
     * @return the value of cw_competition_charge.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.modifier_name
     *
     * @param modifierName the value for cw_competition_charge.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.gmt_modified
     *
     * @return the value of cw_competition_charge.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.gmt_modified
     *
     * @param gmtModified the value for cw_competition_charge.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.charge_name
     *
     * @return the value of cw_competition_charge.charge_name
     *
     * @mbg.generated
     */
    public String getChargeName() {
        return chargeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.charge_name
     *
     * @param chargeName the value for cw_competition_charge.charge_name
     *
     * @mbg.generated
     */
    public void setChargeName(String chargeName) {
        this.chargeName = chargeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition_charge.competition_id
     *
     * @return the value of cw_competition_charge.competition_id
     *
     * @mbg.generated
     */
    public Integer getCompetitionId() {
        return competitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition_charge.competition_id
     *
     * @param competitionId the value for cw_competition_charge.competition_id
     *
     * @mbg.generated
     */
    public void setCompetitionId(Integer competitionId) {
        this.competitionId = competitionId;
    }
}