package com.tencent.wxcloudrun.domain.common;

import java.math.BigDecimal;
import java.util.Date;

public class CwCompetition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.competition_name
     *
     * @mbg.generated
     */
    private String competitionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.competition_img_url
     *
     * @mbg.generated
     */
    private String competitionImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.competition_time
     *
     * @mbg.generated
     */
    private String competitionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.competition_location
     *
     * @mbg.generated
     */
    private String competitionLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.application_start_time
     *
     * @mbg.generated
     */
    private Date applicationStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.application_end_time
     *
     * @mbg.generated
     */
    private Date applicationEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.competition_max_num
     *
     * @mbg.generated
     */
    private Integer competitionMaxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.application_max_num
     *
     * @mbg.generated
     */
    private Integer applicationMaxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.competition_group
     *
     * @mbg.generated
     */
    private String competitionGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.refund_end_time
     *
     * @mbg.generated
     */
    private Date refundEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.refund_free_time
     *
     * @mbg.generated
     */
    private Date refundFreeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.refund_cost_percent
     *
     * @mbg.generated
     */
    private BigDecimal refundCostPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.competition_status
     *
     * @mbg.generated
     */
    private Integer competitionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_competition.competition_text
     *
     * @mbg.generated
     */
    private String competitionText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.id
     *
     * @return the value of cw_competition.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.id
     *
     * @param id the value for cw_competition.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.is_deleted
     *
     * @return the value of cw_competition.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.is_deleted
     *
     * @param isDeleted the value for cw_competition.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.creator_id
     *
     * @return the value of cw_competition.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.creator_id
     *
     * @param creatorId the value for cw_competition.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.creator_name
     *
     * @return the value of cw_competition.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.creator_name
     *
     * @param creatorName the value for cw_competition.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.gmt_create
     *
     * @return the value of cw_competition.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.gmt_create
     *
     * @param gmtCreate the value for cw_competition.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.modifier_id
     *
     * @return the value of cw_competition.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.modifier_id
     *
     * @param modifierId the value for cw_competition.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.modifier_name
     *
     * @return the value of cw_competition.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.modifier_name
     *
     * @param modifierName the value for cw_competition.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.gmt_modified
     *
     * @return the value of cw_competition.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.gmt_modified
     *
     * @param gmtModified the value for cw_competition.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.competition_name
     *
     * @return the value of cw_competition.competition_name
     *
     * @mbg.generated
     */
    public String getCompetitionName() {
        return competitionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.competition_name
     *
     * @param competitionName the value for cw_competition.competition_name
     *
     * @mbg.generated
     */
    public void setCompetitionName(String competitionName) {
        this.competitionName = competitionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.competition_img_url
     *
     * @return the value of cw_competition.competition_img_url
     *
     * @mbg.generated
     */
    public String getCompetitionImgUrl() {
        return competitionImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.competition_img_url
     *
     * @param competitionImgUrl the value for cw_competition.competition_img_url
     *
     * @mbg.generated
     */
    public void setCompetitionImgUrl(String competitionImgUrl) {
        this.competitionImgUrl = competitionImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.competition_time
     *
     * @return the value of cw_competition.competition_time
     *
     * @mbg.generated
     */
    public String getCompetitionTime() {
        return competitionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.competition_time
     *
     * @param competitionTime the value for cw_competition.competition_time
     *
     * @mbg.generated
     */
    public void setCompetitionTime(String competitionTime) {
        this.competitionTime = competitionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.competition_location
     *
     * @return the value of cw_competition.competition_location
     *
     * @mbg.generated
     */
    public String getCompetitionLocation() {
        return competitionLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.competition_location
     *
     * @param competitionLocation the value for cw_competition.competition_location
     *
     * @mbg.generated
     */
    public void setCompetitionLocation(String competitionLocation) {
        this.competitionLocation = competitionLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.application_start_time
     *
     * @return the value of cw_competition.application_start_time
     *
     * @mbg.generated
     */
    public Date getApplicationStartTime() {
        return applicationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.application_start_time
     *
     * @param applicationStartTime the value for cw_competition.application_start_time
     *
     * @mbg.generated
     */
    public void setApplicationStartTime(Date applicationStartTime) {
        this.applicationStartTime = applicationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.application_end_time
     *
     * @return the value of cw_competition.application_end_time
     *
     * @mbg.generated
     */
    public Date getApplicationEndTime() {
        return applicationEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.application_end_time
     *
     * @param applicationEndTime the value for cw_competition.application_end_time
     *
     * @mbg.generated
     */
    public void setApplicationEndTime(Date applicationEndTime) {
        this.applicationEndTime = applicationEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.competition_max_num
     *
     * @return the value of cw_competition.competition_max_num
     *
     * @mbg.generated
     */
    public Integer getCompetitionMaxNum() {
        return competitionMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.competition_max_num
     *
     * @param competitionMaxNum the value for cw_competition.competition_max_num
     *
     * @mbg.generated
     */
    public void setCompetitionMaxNum(Integer competitionMaxNum) {
        this.competitionMaxNum = competitionMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.application_max_num
     *
     * @return the value of cw_competition.application_max_num
     *
     * @mbg.generated
     */
    public Integer getApplicationMaxNum() {
        return applicationMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.application_max_num
     *
     * @param applicationMaxNum the value for cw_competition.application_max_num
     *
     * @mbg.generated
     */
    public void setApplicationMaxNum(Integer applicationMaxNum) {
        this.applicationMaxNum = applicationMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.competition_group
     *
     * @return the value of cw_competition.competition_group
     *
     * @mbg.generated
     */
    public String getCompetitionGroup() {
        return competitionGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.competition_group
     *
     * @param competitionGroup the value for cw_competition.competition_group
     *
     * @mbg.generated
     */
    public void setCompetitionGroup(String competitionGroup) {
        this.competitionGroup = competitionGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.refund_end_time
     *
     * @return the value of cw_competition.refund_end_time
     *
     * @mbg.generated
     */
    public Date getRefundEndTime() {
        return refundEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.refund_end_time
     *
     * @param refundEndTime the value for cw_competition.refund_end_time
     *
     * @mbg.generated
     */
    public void setRefundEndTime(Date refundEndTime) {
        this.refundEndTime = refundEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.refund_free_time
     *
     * @return the value of cw_competition.refund_free_time
     *
     * @mbg.generated
     */
    public Date getRefundFreeTime() {
        return refundFreeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.refund_free_time
     *
     * @param refundFreeTime the value for cw_competition.refund_free_time
     *
     * @mbg.generated
     */
    public void setRefundFreeTime(Date refundFreeTime) {
        this.refundFreeTime = refundFreeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.refund_cost_percent
     *
     * @return the value of cw_competition.refund_cost_percent
     *
     * @mbg.generated
     */
    public BigDecimal getRefundCostPercent() {
        return refundCostPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.refund_cost_percent
     *
     * @param refundCostPercent the value for cw_competition.refund_cost_percent
     *
     * @mbg.generated
     */
    public void setRefundCostPercent(BigDecimal refundCostPercent) {
        this.refundCostPercent = refundCostPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.competition_status
     *
     * @return the value of cw_competition.competition_status
     *
     * @mbg.generated
     */
    public Integer getCompetitionStatus() {
        return competitionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.competition_status
     *
     * @param competitionStatus the value for cw_competition.competition_status
     *
     * @mbg.generated
     */
    public void setCompetitionStatus(Integer competitionStatus) {
        this.competitionStatus = competitionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_competition.competition_text
     *
     * @return the value of cw_competition.competition_text
     *
     * @mbg.generated
     */
    public String getCompetitionText() {
        return competitionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_competition.competition_text
     *
     * @param competitionText the value for cw_competition.competition_text
     *
     * @mbg.generated
     */
    public void setCompetitionText(String competitionText) {
        this.competitionText = competitionText;
    }
}