package com.tencent.wxcloudrun.domain.common;

import java.math.BigDecimal;
import java.util.Date;

public class CwRefundDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.refund_id
     *
     * @mbg.generated
     */
    private Integer refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.player_id
     *
     * @mbg.generated
     */
    private Integer playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.charge_id
     *
     * @mbg.generated
     */
    private Integer chargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.refund_amount
     *
     * @mbg.generated
     */
    private BigDecimal refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.refund_cost_amount
     *
     * @mbg.generated
     */
    private BigDecimal refundCostAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_refund_detail.refund_cost_percent
     *
     * @mbg.generated
     */
    private BigDecimal refundCostPercent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.id
     *
     * @return the value of cw_refund_detail.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.id
     *
     * @param id the value for cw_refund_detail.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.is_deleted
     *
     * @return the value of cw_refund_detail.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.is_deleted
     *
     * @param isDeleted the value for cw_refund_detail.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.creator_id
     *
     * @return the value of cw_refund_detail.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.creator_id
     *
     * @param creatorId the value for cw_refund_detail.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.creator_name
     *
     * @return the value of cw_refund_detail.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.creator_name
     *
     * @param creatorName the value for cw_refund_detail.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.gmt_create
     *
     * @return the value of cw_refund_detail.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.gmt_create
     *
     * @param gmtCreate the value for cw_refund_detail.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.modifier_id
     *
     * @return the value of cw_refund_detail.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.modifier_id
     *
     * @param modifierId the value for cw_refund_detail.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.modifier_name
     *
     * @return the value of cw_refund_detail.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.modifier_name
     *
     * @param modifierName the value for cw_refund_detail.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.gmt_modified
     *
     * @return the value of cw_refund_detail.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.gmt_modified
     *
     * @param gmtModified the value for cw_refund_detail.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.refund_id
     *
     * @return the value of cw_refund_detail.refund_id
     *
     * @mbg.generated
     */
    public Integer getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.refund_id
     *
     * @param refundId the value for cw_refund_detail.refund_id
     *
     * @mbg.generated
     */
    public void setRefundId(Integer refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.player_id
     *
     * @return the value of cw_refund_detail.player_id
     *
     * @mbg.generated
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.player_id
     *
     * @param playerId the value for cw_refund_detail.player_id
     *
     * @mbg.generated
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.charge_id
     *
     * @return the value of cw_refund_detail.charge_id
     *
     * @mbg.generated
     */
    public Integer getChargeId() {
        return chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.charge_id
     *
     * @param chargeId the value for cw_refund_detail.charge_id
     *
     * @mbg.generated
     */
    public void setChargeId(Integer chargeId) {
        this.chargeId = chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.refund_amount
     *
     * @return the value of cw_refund_detail.refund_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.refund_amount
     *
     * @param refundAmount the value for cw_refund_detail.refund_amount
     *
     * @mbg.generated
     */
    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.refund_cost_amount
     *
     * @return the value of cw_refund_detail.refund_cost_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRefundCostAmount() {
        return refundCostAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.refund_cost_amount
     *
     * @param refundCostAmount the value for cw_refund_detail.refund_cost_amount
     *
     * @mbg.generated
     */
    public void setRefundCostAmount(BigDecimal refundCostAmount) {
        this.refundCostAmount = refundCostAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_refund_detail.refund_cost_percent
     *
     * @return the value of cw_refund_detail.refund_cost_percent
     *
     * @mbg.generated
     */
    public BigDecimal getRefundCostPercent() {
        return refundCostPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_refund_detail.refund_cost_percent
     *
     * @param refundCostPercent the value for cw_refund_detail.refund_cost_percent
     *
     * @mbg.generated
     */
    public void setRefundCostPercent(BigDecimal refundCostPercent) {
        this.refundCostPercent = refundCostPercent;
    }
}