package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.domain.common.CwApplication;
import com.tencent.wxcloudrun.domain.common.CwApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CwApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    long countByExample(CwApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    int deleteByExample(CwApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    int insert(CwApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    int insertSelective(CwApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    List<CwApplication> selectByExample(CwApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    CwApplication selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CwApplication record, @Param("example") CwApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CwApplication record, @Param("example") CwApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CwApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CwApplication record);
}