package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.domain.common.CwBanner;
import com.tencent.wxcloudrun.domain.common.CwBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CwBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    long countByExample(CwBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    int deleteByExample(CwBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    int insert(CwBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    int insertSelective(CwBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    List<CwBanner> selectByExample(CwBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    CwBanner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CwBanner record, @Param("example") CwBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CwBanner record, @Param("example") CwBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CwBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CwBanner record);
}