package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.domain.common.CwChargeDetail;
import com.tencent.wxcloudrun.domain.common.CwChargeDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CwChargeDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    long countByExample(CwChargeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    int deleteByExample(CwChargeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    int insert(CwChargeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    int insertSelective(CwChargeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    List<CwChargeDetail> selectByExample(CwChargeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    CwChargeDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CwChargeDetail record, @Param("example") CwChargeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CwChargeDetail record, @Param("example") CwChargeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CwChargeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_charge_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CwChargeDetail record);
}