package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.domain.common.CwCommonPlayer;
import com.tencent.wxcloudrun.domain.common.CwCommonPlayerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CwCommonPlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    long countByExample(CwCommonPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    int deleteByExample(CwCommonPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    int insert(CwCommonPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    int insertSelective(CwCommonPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    List<CwCommonPlayer> selectByExample(CwCommonPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    CwCommonPlayer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CwCommonPlayer record, @Param("example") CwCommonPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CwCommonPlayer record, @Param("example") CwCommonPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CwCommonPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_common_player
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CwCommonPlayer record);
}