package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.domain.common.CwRefundDetail;
import com.tencent.wxcloudrun.domain.common.CwRefundDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CwRefundDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    long countByExample(CwRefundDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    int deleteByExample(CwRefundDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    int insert(CwRefundDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    int insertSelective(CwRefundDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    List<CwRefundDetail> selectByExample(CwRefundDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    CwRefundDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CwRefundDetail record, @Param("example") CwRefundDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CwRefundDetail record, @Param("example") CwRefundDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CwRefundDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_refund_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CwRefundDetail record);
}