package com.tencent.wxcloudrun.dto;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class CompetitionRequest {
  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.competition_name
   *
   * @mbg.generated
   */
  private String competitionName;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.competition_img_url
   *
   * @mbg.generated
   */
  private String competitionImgUrl;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.competition_time
   *
   * @mbg.generated
   */
  private String competitionTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.competition_location
   *
   * @mbg.generated
   */
  private String competitionLocation;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.application_start_time
   *
   * @mbg.generated
   */
  private Date applicationStartTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.application_end_time
   *
   * @mbg.generated
   */
  private Date applicationEndTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.competition_max_num
   *
   * @mbg.generated
   */
  private Integer competitionMaxNum;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.application_max_num
   *
   * @mbg.generated
   */
  private Integer applicationMaxNum;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.competition_group
   *
   * @mbg.generated
   */
  private String competitionGroup;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.refund_end_time
   *
   * @mbg.generated
   */
  private Date refundEndTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.refund_free_time
   *
   * @mbg.generated
   */
  private Date refundFreeTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.refund_cost_percent
   *
   * @mbg.generated
   */
  private BigDecimal refundCostPercent;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.competition_status
   *
   * @mbg.generated
   */
  private Integer competitionStatus;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cw_competition.competition_text
   *
   * @mbg.generated
   */
  private String competitionText;

}
